### PR TITLE
60 drag and drop

### LINKED ISSUE #10: Set up Firestore Emulator
Set up a way to emulate Firebase locally for testing purposes

Documentation:
[Connect to Firestore Emulator](https://firebase.google.com/docs/emulator-suite/connect_firestore#web-version-9)
[Connect to Firebase Auth](https://firebase.google.com/docs/emulator-suite/connect_auth#web-version-9)

### LINKED ISSUE #60: (Pairing game) Implement drag & drop pairing and showing results
In the pairing game, players should be able to create pairings and view their score after submitting them.

Specs:
- [x] Players can drag an English word to pair with a Turkish word
- [x] Players can tap a paired English word to unpair it (return to the unpaired English words)
- [x] When all English words have been paired, the player can click the "done" button
- [x] After clicking done, a modal pops up with the number of correct pairs (ie. 3/4) and the correct answers to any incorrect pairings.
- [x] Styling should match the current [wireframes](https://www.figma.com/file/Fs7I8BkOKB7RJB5eV7677p/Wirerframes?node-id=176%3A45)

This ticket doesn't include sending information back to Firestore about sessions & rounds.

### PR DESCRIPTION
**Pull request by Octillerysnacker**
Closes #60 . Adds drag and drop game. When the user clicks "done", their score is shown and they can either play again or finish the session.

Some notes:
- Dragging leaves behind a "duplicate" of the word
- Playing again uses the same words as the previous round and does not reshuffle them
- Styling is a bit hacky but it works
- The borders on android are on the outside of selected english words and not the inside

Screenshots:
Initial screen
image
Dragging
image
Placed words
image
Finished game
image
Here's how the game looks for a `numPairs = 4`
image

### CODE REVIEW

**Review by emaela — CHANGES_REQUESTED** [review]
On my phone, I ran into a few issues:

On the drag & drop page
- the words aren't fully visible when they are dragged down to match
- the words aren't centered in their cards
- the done button overlaps with the bottom row of cards

On the score page
- the english words aren't fully visible
- the play again and done buttons are too close to the bottom of the screen
- with 8 pairs, the last row overlaps with the play again button

IMG_3969
IMG_3970
IMG_3971

**Comment by jrosen081** [comment]
@emaela Good calls on all of these. Everything should be updated now!

**Review by emaela — COMMENTED** [review]
Any chance we could make the white outline on placed English words less thick? I don't think it's an issue on larger screens but it looks a little overpowering and makes the words less readable on my screen.

**Review by emaela — APPROVED** [review]
I think it looks good now:

IMG_2C4AEE093797-1

**Pull request merged**
