### PR TITLE
158 home screen redesign

### LINKED ISSUE #158: Implement home screen re-design
Specs:
- [ ] The home screen UI matches the Figma design
- [x] The buttons still lead to their respective pages
- [x] The test button is disabled before the participant's test date
- [x] The test button is enabled on aand after the participant's test date

[Figma for updated home screen](https://www.figma.com/file/VF38OjNZyeKzf1pEenoyXu/Wirerframes-(Copy)?node-id=799%3A23)
Screen Shot 2022-04-10 at 3 07 19 PM

### PR DESCRIPTION
**Pull request by nicolesorial**
Implements the most recent designs: new button styling, new test date styling, new assets.

Definitely needs to be tested on a smaller screen

Screenshots of what it looks like on my iPhone 12:
IMG_5353
IMG_5354

Closes #158

### CODE REVIEW

**Review by emaela — CHANGES_REQUESTED** [review]
It looks really great and everything's working well, just a little cramped on my small phone T.T

Would there be a way to make the image container shorter on smaller screens? We don't necessarily need to show the full background image on all screens, but we do need to show all the buttons, preferably with some padding at the bottom.

Image from iOS (1)

**Comment by nicolesorial** [comment]
> It looks really great and everything's working well, just a little cramped on my small phone T.T
> 
> Would there be a way to make the image container shorter on smaller screens? We don't necessarily need to show the full background image on all screens, but we do need to show all the buttons, preferably with some padding at the bottom.


@emaela  pushed a change, check it out and let me know if that solves the problem for you?

**Comment by emaela** [comment]
What it looks like on my device (as a participant, and as an admin):
IMG_4513
IMG_4514

**Comment by shashjar** [comment]
Participant View:


Admin View:

**Review by shashjar — APPROVED** [review]

**Review by emaela — APPROVED** [review]

**Review by Octillerysnacker — APPROVED** [review]

**Pull request merged**
