### PR TITLE
150 Export round data

### LINKED ISSUE #150: Export learning (round) data
After the implementation of an admin view (#149), add the ability to export the required CSV data from the landing screen for `admin` users.

Requirements:
- [x] Library of choice for CSV generation
- [x] Button-triggered email
- [ ] Email should send to the email addressed registered to the current user
- [x] CSV should include all of the data listed in David's requirements
    - Where they can be found/extrapolated from is listed in #140

### PR DESCRIPTION
**Pull request by nicolesorial**
Adds CSV export functionality: compiles round data into a CSV that is stored locally on the device, then uses the native email system to compose an email with the CSV attached, then deletes the CSV after sending.

Closes #150

### CODE REVIEW

**Comment by emaela** [comment]
Out of curiosity, how difficult would it be to add session number as well, similar to round number?

**Comment by nicolesorial** [comment]
@emaela Definitely not impossible but it would involve a little bit of a refactor -- since the CSV is organized with rounds as rows, it's much easier to get the order of the rounds than it is the sessions. Is it something you want me to look into or are you just curious?

**Comment by nicolesorial** [comment]
> Out of curiosity, how difficult would it be to add session number as well, similar to round number?

@emaela Definitely not impossible but it would involve a little bit of a refactor -- since the CSV is organized with rounds as rows, it's much easier to get the order of the rounds than it is the sessions. Is it something you want me to look into or are you just curious?

**Review by emaela — APPROVED** [review]
LGTM

**Pull request merged**
