### PR TITLE
72 selecting game

### LINKED ISSUE #72: (Selecting game) Implement drag & drop pairing and showing results
In the selecting game, players should be able to drag an English word to match with one of many Turkish words, then view receive feedback on whether they were correct and the correct English meaning for each Turkish word.

Specs:

- [x]  Players can drag the English word to pair with a Turkish word
- [x]  Players can tap the paired English word to unpair it
- [x]  When all English words have been paired, the player can click the "done" button
- [x]  Clicking done navigates to a feedback screen
- [x] The feedback screen shows "incorrect" or "correct" based on if the player was right
- [x] The correct English words are shown for all Turkish words

This ticket doesn't include sending information back to Firestore about sessions & rounds.

### PR DESCRIPTION
**Pull request by Octillerysnacker**
Added the selecting game as well updated the styles. Closes #72 and #67 and #78

### CODE REVIEW

**Review by emaela — CHANGES_REQUESTED** [review]
The sizing of the cards isn't consistent (screenshot below)

It's important to David that the cards are always the same size for both games, regardless of numPairs, so also double check that the size is the same the matching game.

**Comment by jrosen081** [comment]
@emaela I don't see a screenshot

**Comment by jrosen081** [comment]
That being said, I think I understood what you meant and fixed it. LMK if it is not fixed

**Comment by emaela** [comment]
> @emaela I don't see a screenshot

Oh shoot sorry, this is what I meant to add:
IMG_3987

**Review by emaela — APPROVED** [review]
Looks right now:

IMG_3989

**Pull request merged**
